// Service Worker for offline support
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

cleanupOutdatedCaches()

// Precache all assets generated by VitePWA
precacheAndRoute(self.__WB_MANIFEST)

self.skipWaiting()
clientsClaim()

// ----------------------------
// Custom fetch handler for API fallback ONLY
// ----------------------------
self.addEventListener('fetch', (event) => {
  const request = event.request

  if (request.url.includes('/api/')) {
    event.respondWith(
      fetch(request).catch(() => caches.match('/offline.html'))
    )
  }
})
